#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Run startup performance tests on the most recent version of Fenix nightly
# for each of the three use cases.

iamhere=${BASH_SOURCE%/*}
iwashere=`pwd`
iamhere=${iamhere/./${iwashere}}
cd ${iamhere}

. common.sh

# Define "parameters" needed to execute all the tests. These names should
# be self explanatory. See README.md for customization information.
homeactivity_start_command='am start-activity org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity'
applink_start_command='am start-activity -t "text/html" -d "about:blank" -a android.intent.action.VIEW org.mozilla.fenix.nightly/org.mozilla.fenix.IntentReceiverActivity'
apk_url_template="https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/project.mobile.fenix.v2.nightly.DATE.latest/artifacts/public/build/armeabi-v7a/geckoNightly/target.apk"
log_dir=/home/hawkinsw/run_logs/
test_date=`date +"%Y.%m.%d"`
log_base=${test_date}
run_log="${log_dir}/${log_base}.log"
downloaded_apk_path=`printf "%s/%s/" \`pwd\` \`date +"%Y/%m/%d"\``;
downloaded_apk_file=`printf "%s/%s" ${downloaded_apk_path} nightly.apk`;
apk_downloaded=0
apk_download_attempts=5

# Create, if necesary all the files and directories needed to store the
# log files generated by running the tests.
maybe_create_dir ${log_dir}
maybe_create_file ${run_log}
maybe_create_dir ${downloaded_apk_path}

maybe_create_file "${log_dir}/${log_base}-ha.log"
maybe_create_file "${log_dir}/${log_base}-al.log"
maybe_create_file "${log_dir}/${log_base}-hanoob.log"

# Do the actual work! All diagnostic output from these actions will
# be logged to _run_log_.
{

  # Try _apk_download_attempts times to download the apk to test.
  for i in `seq 1 ${apk_download_attempts}`; do
    download_apk ${apk_url_template} ${test_date} ${downloaded_apk_file}
    result=$?
    if [ ${result} -eq 0 ]; then
      apk_downloaded=1
      break
    fi
    echo "Trying again to download the nightly apk (error ${result})."
  done

  # Check to see if we could download an apk.
  if [ ${apk_downloaded} -eq 0 ]; then
    echo "Error: Failed to download an APK."
  else
    # Run each of the three use cases 10 times.
    echo "Running tests"
    run_test ${downloaded_apk_file} "${log_dir}/${log_base}-ha.log" "org.mozilla.fenix.nightly" "${homeactivity_start_command}" 100
    run_test ${downloaded_apk_file} "${log_dir}/${log_base}-al.log" "org.mozilla.fenix.nightly" "${applink_start_command}" 25
    run_test ${downloaded_apk_file} "${log_dir}/${log_base}-hanoob.log" "org.mozilla.fenix.nightly" "${homeactivity_start_command}" 100 true
  fi
} >> ${run_log} 2>&1

# Assume that the files in _log_dir_ are under git version control. Update
# that repository with the files that were just generated and push updates
# to the repository's master branch at the remote named fenix-mobile.
cwd=`pwd`
cd ${log_dir}
sweep_files_older_than 30 ${log_dir}
git add *.log
git commit -m "${log_base} test"
git push fenix-mobile master -q
cd ${cwd}


cd ${iwashere}
